spring:
  application:
    name: payment-channels
  profiles:
    active: @profileActive@
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/eNets/
    suffix: .html

feign:
  hystrix:
    enabled: true



mybatis:
  mapper-locations: classpath:mapper/*.xml     #mapper文件路径
  type-aliases-package: com.payment.channels.entity   #实体类的包路径
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

#==================== 日志  ============================
logging:
  config: classpath:logback.xml
