server:
  port: 8761

eureka:
  instance:
    hostname: eurekaB
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #注册中心地址
#      defaultZone: http://eurekaA:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
