server:
  port: 8761

eureka:
  instance:
    hostname: eurekaA
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://eurekaB:8762/eureka/
