server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://47.90.37.64:3306/asianwallet_institution?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhongha-2019
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # rabbitMq 配置
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin@20190319

# redis 配置
redis:
  database: 0
  password: h3m9aMVHC1GiCkTnLH9J
  host: 127.0.0.1
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  #AD3给亚洲钱包提供的商户号
  merchantCode: 20190524500137

  product:
    email:
    mobile:
  developer:
    email: 2502610582@qq.com
    mobile: 18537639396
  operation:
    email:
    mobile:


#项目自定义配置
file:
  tmpfile: /usr/local/tomcat8.5/webapps/tmp
