server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.124.22:3306/asianwallet_institution?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  #文件上传文件大小的设置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
redis:
  database: 0
  password: test123
  host: 192.168.124.22
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

security:
  jwt:
    secret: uplus0000a1ed52710d4533bde25be6da0
    token_expire_hour: 24

#项目自定义配置
file:
  http:
    server: http://192.168.124.31:8080
  upload:
    path: C:\apache-tomcat-8.5.38\webapps
  tmpfile: C:\apache-tomcat-8.5.38\webapps\tmp