server:
  port: 9006

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaA:8761/eureka/,http://eurekaB:8762/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://db.asia:3306/asianwallet_institution?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: asianwallets
    password: QJI1Zh((FSFAyAAf
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    # rabbitMq 配置
  rabbitmq:
    addresses: mq01.asia:5672,mq02.asia:5672
    username: admin
    password: C4wtEiB8GPkSXqfi

# redis 配置
redis:
  database: 0
  password: Uj7cELl8emRBqPEE
  host: redis.asia
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  product:
    email:
    mobile:
  developer:
    email: 2502610582@qq.com
    mobile: 18537639396
  operation:
    email:
    mobile:
  #XE汇率API
  xe:
    accountId: personaltestuse17617711
    apiKey: cejpv7epaok9pqbtrne0pvtuml
  #Open汇率API
  open:
    appId: d69d8cb6dd6f45a6bb569c6279dce5b2
