server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://db.asia:3306/asianwallet_institution?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: asianwallets
    password: QJI1Zh((FSFAyAAf
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
redis:
  database: 0
  password: Uj7cELl8emRBqPEE
  host: redis.asia
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:

###国际短信配置
sms:
  send:
    api:
      inter:
        account: I3041456
        pwd: 1f5SgI6rK77d4e
        intapi: http://intapi.253.com/send/json

      ###普通短信配置
      simple:
        account: N6611753
        pwd: R4VljTqHwr51ec
        batchSendSM: http://smssh1.253.com/msg/HttpBatchSendSM

###邮箱配置
msg:
  send:
    api:
      simple:
        account: asianwallets_test_o4fkUZ
        key: FpCvIVQtQsRSd32A
        name: asianwallets
        url: http://api.sendcloud.net/apiv2/mail/send
      emailFrom: info@asianwallets.com